app:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000

file:
  dir: D:/download/greengram4/

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.84:3306/greengram4
    username: root
    password: green502

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8080
#  ssl:
#    key-store: keystore.p12
#    key-store-type: PKCS12
#    key-store-password: greengram

fcm:
  certification: serviceAccountKey.json


---

spring:
  config:
    activate:
      on-profile: "prod1"
  datasource:
    url: jdbc:mariadb://192.168.0.84:3306/greengram4
    password: green502

file:
  dir: /home/download/
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: "prod2"
server:
  port: 8082